### ISSUE TITLE
Cannot find module './api/skins/nicknames/nicknames'

### ISSUE THREAD

**Issue by stebaker92** [Pharuxtan/fallguys-api#1]
Hi - using the latest version (1.1.0) i'm getting the following error:
`Cannot find module './api/skins/nicknames/nicknames'` in the following file: `node_modules/fallguys-api/lib/fallguys.js`

I've managed to replicate this via github actions (using linux) and using runkit:
https://npm.runkit.com/fallguys-api

**Comment by stebaker92** [comment]
I believe my PR should fix the issue: 
https://github.com/pharuxtan/fallguys-api/pull/2

**Comment by Pit896** [comment]
go inside node_modules: "fallguys-api/lib/api/skins/nicknames" and change nickanames.js in Nicknames.jsin nicknames.js

**Comment by pharuxtan** [comment]
Fixed in 1.1.1 ^^
